import type { CalibrationProfile } from "./calibration-types";

// AUTO-GENERATED by scripts/write-calibration.ts. Do not edit manually.
export const DEFAULT_CALIBRATION_PROFILE: CalibrationProfile = {
  "profile": "web_baseline_v1",
  "method": "percentile",
  "stats": {
    "count": 20,
    "mean": 41.55,
    "median": 45,
    "std": 15.46,
    "min": 0,
    "max": 69
  },
  "sortedRawScores": [
    0,
    21,
    21,
    25,
    34,
    35,
    36,
    41,
    44,
    45,
    45,
    45,
    46,
    47,
    55,
    55,
    55,
    56,
    56,
    69
  ],
  "target": {
    "mean": 70,
    "std": 15
  }
};
