export const BASELINE_SITES = [
  "https://www.google.com",
  "https://www.youtube.com",
  "https://gemini.google.com",
  "https://github.com",
  "https://developer.mozilla.org",
  "https://openai.com",
  "https://vercel.com",
  "https://stripe.com",
  "https://www.cloudflare.com",
  "https://aws.amazon.com",
  "https://learn.microsoft.com",
  "https://stackoverflow.com",
  "https://www.notion.so",
  "https://medium.com",
  "https://substack.com",
  "https://www.reddit.com",
  "https://www.amazon.com",
  "https://www.bbc.com",
  "https://www.nytimes.com",
  "https://www.shopify.com",
] as const;
