import fs from "node:fs/promises";
import path from "node:path";

type CalibrationProfile = {
  profile: string;
  method: "percentile" | "zscore";
  stats: {
    count: number;
    mean: number;
    median: number;
    std: number;
    min: number;
    max: number;
  };
  sortedRawScores: number[];
  target?: {
    mean: number;
    std: number;
  };
};

function toTsModule(profile: CalibrationProfile): string {
  return `import type { CalibrationProfile } from "./calibration-types";

// AUTO-GENERATED by scripts/write-calibration.ts. Do not edit manually.
export const DEFAULT_CALIBRATION_PROFILE: CalibrationProfile = ${JSON.stringify(
    profile,
    null,
    2,
  )};
`;
}

async function main(): Promise<void> {
  const profilePath = path.resolve("generated", "baseline-profile.json");
  const tsOutPath = path.resolve("src", "analyzer", "calibration-baseline.ts");

  const profile = JSON.parse(
    await fs.readFile(profilePath, "utf8"),
  ) as CalibrationProfile;

  await fs.writeFile(tsOutPath, toTsModule(profile), "utf8");

  console.log(`Wrote ${tsOutPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
